### ISSUE TITLE
[Enhancement] update `about-text` the effect of hyperlink

### ISSUE THREAD

**Issue by 1chooo** [1chooo/vcard#101]
sync with timeline-text effect

```css
.timeline-text a {
    display: inline;
    color: var(--orange-yellow-crayola);
    text-decoration: underline;
    font-weight: bold;
}

.timeline-text a:hover {
    text-decoration-color: hsla(0, 0%, 84%, 0.7);
}
```
