### ISSUE TITLE
The screen ratio issue on iPhone 11

### ISSUE THREAD

**Issue by 1chooo** [1chooo/vcard#11]
To address the screen problem at 375 pixels, please add the following to `App.css`:

```css
/**
* responsive larger than 375px screen
*/

@media (min-width: 375px) {

    /**
    * client
    */

    .clients-item {
        min-width: calc(33.33% - 10px);
    }


    .techstack-item {
        min-width: calc(10% - 20px);
    }



    /**
    * #PORTFOLIO, BLOG 
    */

    .project-img,
    .blog-banner-box {
        height: auto;
    }

}
```

Screenshots:

![IMG_3297](https://github.com/1chooo/1chooo.com/assets/94162591/f0fd9f4e-0bb8-48a5-98c2-35cc9880e268)
