### ISSUE TITLE
[Refactor] Simplifying Page Display Logic by Adjusting `article` Element 

### ISSUE THREAD

**Issue by 1chooo** [1chooo/vcard#118]
The reason for the current implementation:

https://github.com/1chooo/1chooo.com/blob/7c059b7eceea605a022e7a39c57861b19e6ba591/src/components/page-content.tsx#L26

is due to the following design in our `global.css`:

```css
article {
  display: none;
}

article.active {
  display: block;
  animation: fade 0.5s ease backwards;
}
```

If we change the `article` to be directly visible, we won't need to determine the `className` to display the page, potentially reducing redundant content in `global.css`:

```css
article {
  display: block;
  animation: fade 0.5s ease backwards;
}
```

related: #81
