### ISSUE TITLE
The `info_more-btn` issue on iPad 

### ISSUE THREAD

**Issue by 1chooo** [1chooo/vcard#12]
The `<MdExpandMore />` icon within the `info_more-btn` class is initially invisible when viewing the webpage on an iPad. However, it is only displayed in phone mode. To ensure it not appears on screens larger than 580px, add the following style:

```css
.info_more-btn svg {
    display: none;
}
```

This CSS code will make the `<MdExpandMore />` icon invisible when the screen width is larger than 580px.
