### ISSUE TITLE
[Feature] Add timeline-text `<li>` `list-style`

### ISSUE THREAD

**Issue by 1chooo** [1chooo/vcard#207]
The current `list-style` in timeline-text is not displayed because the global css is 

```css
li {
  list-style: none;
}
```

therefore, we have to add 

```css
.timeline-text li {
    list-style: disc;
}
```

or we can not render list successfully.
