### ISSUE TITLE
[Feature] add list-style in post

### ISSUE THREAD

**Issue by 1chooo** [1chooo/vcard#221]
The current list styles is not successfully rendered in the post page

```css
.li {
    list-style: disc;
}
```

related: #190, #217
