### ISSUE TITLE
[Feature] Limit Blog Post Summary to Two Lines with Ellipsis

### ISSUE THREAD

**Issue by 1chooo** [1chooo/vcard#303]
### **Description:**
The blog post summary (`summary`) on the blog page currently displays the entire content, which can make the layout inconsistent and cluttered when the text is long. We need to limit the summary to a maximum of **two lines** and show an ellipsis (`...`) when the content exceeds that limit.

### **Current Behavior:**
- The full summary text is being displayed without truncation, causing blog posts with long summaries to take up excessive vertical space.
- This leads to inconsistent heights across blog posts and a visually cluttered interface.

### **Expected Behavior:**
- The summary text should be truncated to **two lines**.
- If the text exceeds two lines, an ellipsis (`...`) should appear at the end.
- The visual appearance (font size, weight, and color) should remain consistent with the current design.

### **Proposed Solution:**
- Use the `-webkit-line-clamp` CSS property to limit the text to two lines and append an ellipsis for overflowing content.

### **Steps to Implement:**
1. Update the `.blog-text` class in the CSS file with the following:
   ```css
   .blog-text {
     color: var(--light-gray);
     font-size: var(--fs-6);
     font-weight: var(--fw-300);
     line-height: 1.6;

     display: -webkit-box;
     -webkit-line-clamp: 2; /* Limit to 2 lines */
     -webkit-box-orient: vertical;
     overflow: hidden;
     text-overflow: ellipsis;
     white-space: normal;
   }
   ```

2. Verify that the updated `.blog-text` class is properly applied to the `MarkdownRenderer` component that renders the `summary` text.

3. Ensure that the summary is correctly truncated with an ellipsis when the content exceeds two lines, across different screen sizes.
